[project]
name = "medium-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pinecone>=6.0.2",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]
