[project]
name = "fhir-resources-protocol-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pdfplumber>=0.11.6",
    "requests>=2.32.3",
    "urllib3>=2.4.0",
]
